

services:
  app:
    container_name: mihara-tt-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      -  ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mihara-tt-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    container_name: mihara-tt-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  node:
    container_name: mihara-tt-node
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html 
    tty: true
    depends_on:
      - app

  phpmyadmin:
    container_name: mihara-tt-phpmyadmin
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  db-data: